
#ifndef __constants_h__
#define __constants_h__
char OPTPROCESSOR_API[100];

char OPTPROCESSOR_DBOPS_API[100];

char OPTPROCESSOR_BING_API[100];

char SHOPPINGPROCESSOR_API[100];

char SHOPPINGPROCESSOR_DBOPS_API[100];

char SHOPPINGPROCESSOR_BING_API[100];

#endif